### ISSUE TITLE
Error when map has no background image (?)

### ISSUE THREAD

**Issue by Yokkako** [Ludeo/intralism-tool-collection#9]
tried to convert my map and it gave me this error (the map doesnt have a BG image so idk why it says cant find it)

System.IO.FileNotFoundException: Could not find file 'D:\Programme\osu!\Songs\455-38B_-_G_e_n_g_a_o_z_o_-_f_o_o_n\BG.jpg'.
File name: 'D:\Programme\osu!\Songs\455-38B_-_G_e_n_g_a_o_z_o_-_f_o_o_n\BG.jpg'
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at IntralismManiaConverter.Converter.SaveImages(String rootPath, String outputFolder, IEnumerable`1 backgroundFileNames)
   at IntralismManiaConverter.Converter.SaveFiles(String pathToBeatmapFile, String outputFolder, String audioFilename, IStoryboardable backgroundFileNames, ISavable savable)
   at IntralismManiaConverter.Converter.AsyncConvertManiaToIntralism(String pathToBeatmapFile, String outputFolder, Double speed)
   at IntralismToolBox.Forms.MainForm.ConvertToIntralismClicked(Object sender, EventArgs e) in C:\Coding\C#\IntralismToolBox\IntralismToolBox\Src\Forms\MainForm.cs:line 162
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)

************** Geladene Assemblys **************
System.Private.CoreLib
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Private.CoreLib.dll.
----------------------------------------
IntralismToolBox
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///D:/Benutzer/Felix/Desktop/Intralism%20Tool%20Box%20Release/IntralismToolBox.dll.
----------------------------------------
System.Runtime
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Runtime.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 5.0.1.0.
    Win32-Version: 5.0.120.57506.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/System.Windows.Forms.dll.
----------------------------------------
System.Windows.Forms.Primitives
    Assembly-Version: 5.0.1.0.
    Win32-Version: 5.0.120.57506.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/System.Windows.Forms.Primitives.dll.
----------------------------------------
System.ComponentModel.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.ComponentModel.Primitives.dll.
----------------------------------------
System.Runtime.InteropServices
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Runtime.InteropServices.dll.
----------------------------------------
System.Drawing.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Drawing.Primitives.dll.
----------------------------------------
System.Collections.Specialized
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Collections.Specialized.dll.
----------------------------------------
System.Drawing.Common
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.20.51904.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/System.Drawing.Common.dll.
----------------------------------------
System.Threading
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Threading.dll.
----------------------------------------
System.Diagnostics.TraceSource
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Diagnostics.TraceSource.dll.
----------------------------------------
System.Collections
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Collections.dll.
----------------------------------------
System.Configuration.ConfigurationManager
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.20.51904.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/System.Configuration.ConfigurationManager.dll.
----------------------------------------
netstandard
    Assembly-Version: 2.1.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/netstandard.dll.
----------------------------------------
Microsoft.Win32.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/Microsoft.Win32.Primitives.dll.
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.ComponentModel.EventBasedAsync.dll.
----------------------------------------
System.Threading.Thread
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Threading.Thread.dll.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 5.0.120.57506.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/Accessibility.dll.
----------------------------------------
System.IO.FileSystem
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.IO.FileSystem.dll.
----------------------------------------
System.Xml.ReaderWriter
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Xml.ReaderWriter.dll.
----------------------------------------
System.Private.Xml
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Private.Xml.dll.
----------------------------------------
System.Net.WebClient
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Net.WebClient.dll.
----------------------------------------
System.Memory
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Memory.dll.
----------------------------------------
System.Security.Cryptography.Algorithms
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Security.Cryptography.Algorithms.dll.
----------------------------------------
System.Text.Encoding.Extensions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Text.Encoding.Extensions.dll.
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.ComponentModel.TypeConverter.dll.
----------------------------------------
System.Runtime.Extensions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Runtime.Extensions.dll.
----------------------------------------
System.Resources.Extensions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.20.51904.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/System.Resources.Extensions.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 5.0.1.0.
    Win32-Version: 5.0.120.57506.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/System.Drawing.dll.
----------------------------------------
System.ObjectModel
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.ObjectModel.dll.
----------------------------------------
System.Linq
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Linq.dll.
----------------------------------------
System.Buffers
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Buffers.dll.
----------------------------------------
System.ComponentModel
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.ComponentModel.dll.
----------------------------------------
System.Private.Uri
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Private.Uri.dll.
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.20.51904.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/Microsoft.Win32.SystemEvents.dll.
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.4200.0.
    CodeBase: file:///D:/Benutzer/Felix/Desktop/Intralism%20Tool%20Box%20Release/System.Windows.Forms.DataVisualization.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.dll.
----------------------------------------
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/mscorlib.dll.
----------------------------------------
Octokit
    Assembly-Version: 0.48.0.0.
    Win32-Version: 0.48.0.0.
    CodeBase: file:///D:/Benutzer/Felix/Desktop/Intralism%20Tool%20Box%20Release/Octokit.dll.
----------------------------------------
System.Net.Http
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Net.Http.dll.
----------------------------------------
System.Net.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Net.Primitives.dll.
----------------------------------------
System.Diagnostics.Tracing
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Diagnostics.Tracing.dll.
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Diagnostics.DiagnosticSource.dll.
----------------------------------------
System.Net.Security
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Net.Security.dll.
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Security.Cryptography.X509Certificates.dll.
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Runtime.InteropServices.RuntimeInformation.dll.
----------------------------------------
System.Collections.Concurrent
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Collections.Concurrent.dll.
----------------------------------------
System.Net.Sockets
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Net.Sockets.dll.
----------------------------------------
System.Net.NameResolution
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Net.NameResolution.dll.
----------------------------------------
System.Threading.Overlapped
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Threading.Overlapped.dll.
----------------------------------------
System.Threading.ThreadPool
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Threading.ThreadPool.dll.
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Security.Cryptography.Primitives.dll.
----------------------------------------
System.Collections.NonGeneric
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Collections.NonGeneric.dll.
----------------------------------------
System.Security.Principal.Windows
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Security.Principal.Windows.dll.
----------------------------------------
System.Security.Claims
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Security.Claims.dll.
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Security.Cryptography.Encoding.dll.
----------------------------------------
System.IO.Compression
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.IO.Compression.dll.
----------------------------------------
System.Text.RegularExpressions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Text.RegularExpressions.dll.
----------------------------------------
System.Linq.Expressions
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Linq.Expressions.dll.
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Reflection.Emit.ILGeneration.dll.
----------------------------------------
System.Reflection.Primitives
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Reflection.Primitives.dll.
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Reflection.Emit.Lightweight.dll.
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly-Version: 0.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Private.CoreLib.dll.
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Runtime.CompilerServices.Unsafe.dll.
----------------------------------------
IntralismManiaConverter
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///D:/Benutzer/Felix/Desktop/Intralism%20Tool%20Box%20Release/IntralismManiaConverter.dll.
----------------------------------------
OsuParsers
    Assembly-Version: 1.6.5.0.
    Win32-Version: 1.6.5.0.
    CodeBase: file:///D:/Benutzer/Felix/Desktop/Intralism%20Tool%20Box%20Release/OsuParsers.dll.
----------------------------------------
System.Numerics.Vectors
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Numerics.Vectors.dll.
----------------------------------------
MoreLinq
    Assembly-Version: 3.3.2.0.
    Win32-Version: 3.3.2.0.
    CodeBase: file:///D:/Benutzer/Felix/Desktop/Intralism%20Tool%20Box%20Release/MoreLinq.dll.
----------------------------------------
System.Data.Common
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Data.Common.dll.
----------------------------------------
NAudio
    Assembly-Version: 1.10.0.0.
    Win32-Version: 1.10.0.0.
    CodeBase: file:///D:/Benutzer/Felix/Desktop/Intralism%20Tool%20Box%20Release/NAudio.dll.
----------------------------------------
NAudio.Vorbis
    Assembly-Version: 1.2.0.1.
    Win32-Version: 1.2.0.1.
    CodeBase: file:///D:/Benutzer/Felix/Desktop/Intralism%20Tool%20Box%20Release/NAudio.Vorbis.dll.
----------------------------------------
FFmpeg.NET
    Assembly-Version: 3.4.0.0.
    Win32-Version: 3.4.0.
    CodeBase: file:///D:/Benutzer/Felix/Desktop/Intralism%20Tool%20Box%20Release/FFmpeg.NET.dll.
----------------------------------------
System.Diagnostics.Process
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Diagnostics.Process.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 5.0.1.0.
    Win32-Version: 5.0.120.57506.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/5.0.1/de/System.Windows.Forms.resources.dll.
----------------------------------------
System.Diagnostics.StackTrace
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Diagnostics.StackTrace.dll.
----------------------------------------
System.Reflection.Metadata
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Reflection.Metadata.dll.
----------------------------------------
System.Collections.Immutable
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Collections.Immutable.dll.
----------------------------------------
System.IO.MemoryMappedFiles
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.IO.MemoryMappedFiles.dll.
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly-Version: 5.0.0.0.
    Win32-Version: 5.0.120.57516.
    CodeBase: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/5.0.1/System.Diagnostics.FileVersionInfo.dll.
----------------------------------------

**Comment by Yokkako** [comment]
can confirm I added an image and it worked lol

**Comment by Ludeo** [comment]
There was probably an image in the .osu file because otherwise the converter wouldn't have a file name but I guess the problem is resolved now ?
